message changed
Meelenych/nodejs-rest-api pull request #1
Opened 2022-01-21 10:13 UTC by Meelenych

2022-01-24 19:06 UTC, KirillKulakow commented on routes/api/contacts-rotes.js
> +// console.log(contacts);
удалить

2022-01-24 19:07 UTC, KirillKulakow commented on app.js
> +// console.log("test", router);
удалить

2022-01-24 19:08 UTC, KirillKulakow commented on app.js
> +	// const { status = 500, message = "Server error!" } = err;
зачем закомментировал?

2022-01-24 19:08 UTC, KirillKulakow commented on models/contacts-funcs.js
> +// const shortid = require("shortid");
удалить

2022-01-24 19:08 UTC, KirillKulakow commented on models/contacts-funcs.js
> +	// console.log(result);
удалить

2022-01-24 19:08 UTC, KirillKulakow commented on models/contacts-funcs.js
> +	// console.log(removedContact);
удалить

2022-01-24 19:08 UTC, KirillKulakow commented on models/contacts-funcs.js
> +	// const newContact = { id: shortid.generate(), name, email, phone };
удалить

2022-01-24 19:08 UTC, KirillKulakow commented on models/contacts-funcs.js
> +	// console.log(newContact);
удалить

2022-01-24 19:08 UTC, KirillKulakow commented on models/contacts-funcs.js
> +	// console.log(contacts[index]);
удалить

2022-01-24 19:09 UTC, KirillKulakow commented on routes/api/contacts-rotes.js
> +		console.log("req.params", req.params.contactId);
удалить

2022-01-24 19:09 UTC, KirillKulakow commented on routes/api/contacts-rotes.js
> +	// console.log("ADD", req.body);
удалить

2022-01-24 19:10 UTC, KirillKulakow commented on routes/api/contacts-rotes.js
> +		// console.log("DELETE,body", req.body);
удалить

2022-01-24 19:10 UTC, KirillKulakow commented on routes/api/contacts-rotes.js
> +		// console.log("UPDATE", req.params);
удалить

2022-01-24 19:11 UTC, KirillKulakow requested changes
Need fix

2022-01-25 21:21 UTC, KirillKulakow commented on models/contacts-funcs.js
> +	console.table(contacts);
удалить

2022-01-25 21:25 UTC, KirillKulakow commented on routes/api/contacts-rotes.js
> +		res.status(201).json(result);
если здесь не поставить return будут node будет пробовать выполнить два вызова res.json, здесь и в самом низу функции

2022-01-25 21:25 UTC, KirillKulakow commented on routes/api/contacts-rotes.js
> +		res.json(result);
по аналогии прошлого коммента

2022-01-25 21:25 UTC, KirillKulakow requested changes
Need fix

2022-01-26 19:04 UTC, KirillKulakow commented on routes/api/contacts-rotes.js
> +		console.log("req.params", req.params.contactId);
не удален

2022-01-26 19:04 UTC, KirillKulakow commented on routes/api/contacts-rotes.js
> +		console.log("req.params", req.params.contactId);
лог

2022-01-26 19:05 UTC, KirillKulakow commented on routes/api/contacts-rotes.js
> +		if (
зачем проверка если есть валидация через схему?

2022-01-26 19:06 UTC, KirillKulakow requested changes
Need fix

2022-01-29 19:51 UTC, Meelenych commented on models/contacts-funcs.js
> +	console.table(contacts);
удалил

2022-01-29 19:51 UTC, Meelenych commented on routes/api/contacts-rotes.js
> +		res.status(201).json(result);
добавил return

2022-01-29 19:51 UTC, Meelenych commented on routes/api/contacts-rotes.js
> +		res.json(result);
добавил return

2022-01-29 19:51 UTC, Meelenych commented on routes/api/contacts-rotes.js
> +		if (
доп. проверку убрал

2022-01-30 07:23 UTC, KirillKulakow approved these changes

2022-02-01 11:56 UTC, merged