hw03 ready
Meelenych/nodejs-rest-api pull request #2
Opened 2022-01-29 22:54 UTC by Meelenych

2022-01-30 07:33 UTC, KirillKulakow commented on routes/api/contacts-routes.js
> +		if (error.message.includes("Cast to ObjectId failed")) {
плохой вариант
сделай проверка на валидность ид через mongoose.Types.ObjectId.isValid, перед выполнением поиска

2022-01-30 07:37 UTC, KirillKulakow commented on routes/api/contacts-routes.js
> +		if (error.message.includes("Validation failed")) {
зачем это?

2022-01-30 07:37 UTC, KirillKulakow commented on routes/api/contacts-routes.js
> +	res.json({ message: "Contact sucessfully added" });
зачем данная строка?

2022-01-30 07:38 UTC, KirillKulakow commented on routes/api/contacts-routes.js
> +		const id = req.params.contactId;
сделать проверку

2022-01-30 07:38 UTC, KirillKulakow commented on routes/api/contacts-routes.js
> +		const id = req.params.contactId;
сделать проверку

2022-01-30 07:39 UTC, KirillKulakow commented on routes/api/contacts-routes.js
> +		} else if (req.body === null) {
смысл данной проверки, если ты уже выполнил запись в базу данных

2022-01-30 07:39 UTC, KirillKulakow commented on routes/api/contacts-routes.js
> +	res.json({ message: "Contact sucessfully updated" });
зачем эта строка?

2022-01-30 07:39 UTC, KirillKulakow commented on routes/api/contacts-routes.js
> +		const id = req.params.contactId;
сделать проверку

2022-01-30 07:40 UTC, KirillKulakow requested changes
need fix

2022-02-13 15:02 UTC, Meelenych commented on routes/api/contacts-routes.js
> +		if (error.message.includes("Validation failed")) {
убрал

2022-02-13 15:02 UTC, Meelenych commented on routes/api/contacts-routes.js
> +	res.json({ message: "Contact sucessfully added" });
убрал

2022-02-13 15:07 UTC, Meelenych commented on routes/api/contacts-routes.js
> +		} else if (req.body === null) {
перенес ее выше

2022-02-13 15:09 UTC, Meelenych commented on routes/api/contacts-routes.js
> +	res.json({ message: "Contact sucessfully updated" });
убрал

2022-02-13 16:00 UTC, Meelenych commented on routes/api/contacts-routes.js
> +		if (error.message.includes("Cast to ObjectId failed")) {
добавил проверку

2022-02-13 16:00 UTC, Meelenych commented on routes/api/contacts-routes.js
> +		const id = req.params.contactId;
добавил проверку

2022-02-13 16:00 UTC, Meelenych commented on routes/api/contacts-routes.js
> +		const id = req.params.contactId;
добавил проверку

2022-02-13 16:00 UTC, Meelenych commented on routes/api/contacts-routes.js
> +		const id = req.params.contactId;
добавил проверку

2022-02-13 16:14 UTC, KirillKulakow commented on routes/api/contacts-routes.js
> +		if (error.message.includes("Cast to ObjectId failed")) {
так а зачем тебе эта проверка, если ты сделал проверку выше?

2022-02-13 16:15 UTC, KirillKulakow approved these changes

2022-02-13 16:22 UTC, Meelenych commented on routes/api/contacts-routes.js
> +		if (error.message.includes("Cast to ObjectId failed")) {
понял, убрал :)

2022-02-16 08:48 UTC, closed without merging