auth added
Meelenych/nodejs-rest-api pull request #3
Opened 2022-02-16 09:00 UTC by Meelenych

2022-02-16 19:49 UTC, KirillKulakow commented on routes/api/contacts-routes.js
> +		const skip = (page - 1) * limit;
перед математическими операциями рекомендую проверять входящие параметры query
например через метод isNaN

2022-02-16 19:50 UTC, KirillKulakow commented on routes/api/contacts-routes.js
> +		if (!result || !contactId) {
смысл проверки !contactId? если он у тебя будет undefined - ошибка будет на строке 78

2022-02-16 19:51 UTC, KirillKulakow commented on routes/api/contacts-routes.js
> +		if (req.body === null) {
зачем тебе эта проверка, если проверка выполняется на строке 93

2022-02-16 19:53 UTC, KirillKulakow commented on routes/api/contacts-routes.js
> +const express = require("express");
исходя из твоего приложения - любой зарегистрированный юзер может удалить/изменить/посмотреть любой контакт в бд
сделай поиск не только по ид контакта но и с учетом ид собственника контакта

2022-02-16 19:53 UTC, KirillKulakow requested changes
Need fix

2022-02-18 08:01 UTC, Meelenych commented on routes/api/contacts-routes.js
> +const express = require("express");
Поправил. Был неправильный метод поиска в контроллере.

2022-02-18 08:01 UTC, Meelenych commented on routes/api/contacts-routes.js
> +		if (req.body === null) {
Убрал.

2022-02-18 08:01 UTC, Meelenych commented on routes/api/contacts-routes.js
> +		if (!result || !contactId) {
Убрал.

2022-02-18 08:01 UTC, Meelenych commented on routes/api/contacts-routes.js
> +		const skip = (page - 1) * limit;
Пытался сделать. Потом начало выбивать ошибку. Не могу понять почему.
 {
    "message": "Cannot do inclusion on field limit in exclusion projection"
}
Закоментировал то, что сделал.

2022-02-18 19:43 UTC, KirillKulakow commented on routes/api/contacts-routes.js
> +const express = require("express");
проблема не исправлена
любой зарегистрированный юзер может делать операции с любым контактом (не важно его этот контакт или нет)

2022-02-18 19:43 UTC, KirillKulakow requested changes
Need fix

2022-02-20 11:09 UTC, Meelenych commented on routes/api/contacts-routes.js
> +const express = require("express");
Добавил owner ID

2022-02-20 15:14 UTC, KirillKulakow approved these changes

2022-02-21 08:14 UTC, merged